# Numpy

**Numeric Python**

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

# numpy.ndarray
# n dimensional data.

array([1, 2, 3, 4, 5])

In [3]:
np.array([1,2,3,4,5,'rishiraj',(4+8j)])

array(['1', '2', '3', '4', '5', 'rishiraj', '(4+8j)'], dtype='<U64')

In [4]:
np.array([1,2,3,4,5,6.0]) # It coverts the data or upcast the data. 
# Whatever is high in level, means floating number takes more memory.

array([1., 2., 3., 4., 5., 6.])

In [5]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [6]:
np.array([[1,2],[3,4],[4,5],[6,7]])

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

* ([1,2,3,4,5]) One dimension array
* ([[1,2],[3,4],[4,5],[6,7]]) Two dimension array

In [7]:
# We can also give dimensions directly.
np.array([1,2,3],ndmin=5)

array([[[[[1, 2, 3]]]]])

In [8]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
arr = np.array([(1,2),(4,5)],dtype = [("a","<i2"),("b","<i8")])
arr

# by giving data type, it will give us a different type as
# shown below.

# In the above example, (1,2) 1,4 = a and 2,5 = b

"""
i2 = 16bits
i4 = 32 bits Default
i8 = 64 bits
# It's the size of the data.
"""

"\ni2 = 16bits\ni4 = 32 bits Default\ni8 = 64 bits\n# It's the size of the data.\n"

In [10]:
type(arr[0][0])

numpy.int16

In [11]:
type(arr[0][1])

numpy.int64

In [12]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

# Matrix

In [13]:
np.mat([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

In [14]:
np.matrix([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

In [15]:
l = [3,4,5,76,7]

In [16]:
np.array(l)

array([ 3,  4,  5, 76,  7])

In [17]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [18]:
np.asanyarray(l) # It will not convert data which is already
# in any type of array.

# Like it won't change Matrix.

array([ 3,  4,  5, 76,  7])

* **Matrix is a subset for array**

In [19]:
# To check if matrix is a subclass of array

issubclass(np.matrix,np.ndarray)

True

In [20]:
issubclass(np.ndarray,np.matrix)

False

# Deep Copy And Shallow Copy

In [21]:
# Array is a mutable datatype.

aru = np.array([[1,2],[3,4]])
aru

array([[1, 2],
       [3, 4]])

In [22]:
a = aru # Shallow Copy (It will change the data)

In [23]:
b = np.copy(aru) # Deep Copy (It won't change the data)

In [24]:
aru[0][0] = 69

In [25]:
aru

array([[69,  2],
       [ 3,  4]])

In [26]:
a

array([[69,  2],
       [ 3,  4]])

In [27]:
b

array([[1, 2],
       [3, 4]])

In [28]:
for i in aru:
    print(i)

[69  2]
[3 4]


# Difference between array and list
**Array belongs to numpy package and mathematical formula which is available inside numpy will be applicable on numpy array directly wherease list is a part of Python core**

In [29]:
np.fromfunction(lambda i,j:i==j,(4,4))

# from function helps to create an array with a logic we give.

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [30]:
np.fromfunction(lambda i,j:i*j,(3,3))


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
np.fromfunction(lambda i,j:i/j,(3,3))

# In numpy we aren't getting an error on 1/0 and 0/0


C:\Users\USER\AppData\Local\Temp\ipykernel_18944\2580751211.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j:i/j,(3,3))
C:\Users\USER\AppData\Local\Temp\ipykernel_18944\2580751211.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j:i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [32]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [33]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [34]:
np.fromstring('1,2,3,4,5',sep=',')

array([1., 2., 3., 4., 5.])

# Difference between Array and Matrix 

Conceptually they both are same but Matrix is a sub class of an Array.

In [35]:
list(range(6)) # In the range function, float datatype will not work.
# We can use numpy's arange. Starting, end and jump should always be an integer in range function. It doesn't include upper bound.

[0, 1, 2, 3, 4, 5]

In [36]:
np.arange(0,5.5) #It accepts float, upper bound also it includes unlike range.
# In case of float it will include upper bound not in the case of integer. (layman way)
# Mathematically, it happens because floating number can go upto infinity and that's why it's included. 
# .3 could be 0.300000000000000000001

array([0., 1., 2., 3., 4., 5.])

In [37]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
np.linspace(1,2,5) # It will create 5 data between 1 to 2.
# If we don't give 5, it will create 50 data.

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [39]:
# 
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.zeros((2,5,4))   # 5*4 in 2 matrix

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [41]:
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
np.ones((2,1,4))+5

array([[[6., 6., 6., 6.]],

       [[6., 6., 6., 6.]]])

In [43]:
np.empty(5) # Create random data.

array([0., 0., 0., 0., 0.])

**Every output is a nd array**

In [44]:
np.eye(3) # Eye = Identity matrix = It is a square matrix =number of columns == number of rows.


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.linspace([0,10],4,axis=1)

array([[ 0.        ,  0.08163265,  0.16326531,  0.24489796,  0.32653061,
         0.40816327,  0.48979592,  0.57142857,  0.65306122,  0.73469388,
         0.81632653,  0.89795918,  0.97959184,  1.06122449,  1.14285714,
         1.2244898 ,  1.30612245,  1.3877551 ,  1.46938776,  1.55102041,
         1.63265306,  1.71428571,  1.79591837,  1.87755102,  1.95918367,
         2.04081633,  2.12244898,  2.20408163,  2.28571429,  2.36734694,
         2.44897959,  2.53061224,  2.6122449 ,  2.69387755,  2.7755102 ,
         2.85714286,  2.93877551,  3.02040816,  3.10204082,  3.18367347,
         3.26530612,  3.34693878,  3.42857143,  3.51020408,  3.59183673,
         3.67346939,  3.75510204,  3.83673469,  3.91836735,  4.        ],
       [10.        ,  9.87755102,  9.75510204,  9.63265306,  9.51020408,
         9.3877551 ,  9.26530612,  9.14285714,  9.02040816,  8.89795918,
         8.7755102 ,  8.65306122,  8.53061224,  8.40816327,  8.28571429,
         8.16326531,  8.04081633,  7.91836735,  7.

In [46]:
np.logspace(2,5)

array([   100.        ,    115.13953993,    132.57113656,    152.64179672,
          175.75106249,    202.35896477,    232.99518105,    268.26957953,
          308.88435965,    355.64803062,    409.49150624,    471.48663635,
          542.86754393,    625.05519253,    719.685673  ,    828.64277285,
          954.09547635,   1098.54114199,   1264.85521686,   1456.3484775 ,
         1676.83293681,   1930.69772888,   2222.99648253,   2559.5479227 ,
         2947.05170255,   3393.2217719 ,   3906.93993705,   4498.43266897,
         5179.47467923,   5963.62331659,   6866.48845004,   7906.04321091,
         9102.98177992,  10481.13134155,  12067.92640639,  13894.95494373,
        15998.58719606,  18420.69969327,  21209.5088792 ,  24420.53094549,
        28117.68697974,  32374.57542818,  37275.93720315,  42919.34260129,
        49417.13361324,  56898.66029018,  65512.85568596,  75431.20063355,
        86851.13737514, 100000.        ])

In [47]:
d = np.linspace(4,7,40)
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [48]:
# To arrange data in different shape.
d.reshape(40,1) # 40 rows and 1 Column

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [49]:
d.reshape(5,1,8) # 1 row and 20 columns

# 5*8 = 40 (Number of data we have, if any other number is given it won't work)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154]],

       [[4.61538462, 4.69230769, 4.76923077, 4.84615385, 4.92307692,
         5.        , 5.07692308, 5.15384615]],

       [[5.23076923, 5.30769231, 5.38461538, 5.46153846, 5.53846154,
         5.61538462, 5.69230769, 5.76923077]],

       [[5.84615385, 5.92307692, 6.        , 6.07692308, 6.15384615,
         6.23076923, 6.30769231, 6.38461538]],

       [[6.46153846, 6.53846154, 6.61538462, 6.69230769, 6.76923077,
         6.84615385, 6.92307692, 7.        ]]])

In [50]:
# To generate random data in gaussion distribution.
np.random.rand(3)

array([0.87671715, 0.64951571, 0.65851476])

In [51]:
np.random.randn(5) # It returns data in standard normal distribution.

array([-0.69043227,  0.29571959, -0.4211494 , -0.76344993, -1.57310241])

In [52]:
np.random.randn(2,3)

array([[-2.96616173, -0.74846375, -1.7639234 ],
       [ 0.60533363, -0.45959525, -2.33652008]])

In [53]:
np.random.randint(5,60,(4,4)) # data between 5-60 in 4-4 matrix.

array([[30, 36, 41,  8],
       [45, 53, 45, 39],
       [ 9, 35, 35, 57],
       [19,  7, 42,  9]])

In [54]:
np.random.randint(5)

1

In [55]:
arr_data = np.random.randint(0,9,(3,3))
arr_data

array([[8, 6, 7],
       [3, 0, 1],
       [5, 5, 6]])

In [56]:
arr_data.reshape(9,1)

array([[8],
       [6],
       [7],
       [3],
       [0],
       [1],
       [5],
       [5],
       [6]])

In [57]:
arr_data.reshape(3,-54545) # We can give any negative number and it will consider the ideal number automatically.

array([[8, 6, 7],
       [3, 0, 1],
       [5, 5, 6]])

In [58]:
arr_data.max()

8

In [59]:
arr_data.min()

0

In [60]:
arrr = np.random.randint(0,100,(5,5))

arrr

array([[ 1, 11, 81, 45,  8],
       [37, 88, 41, 67, 65],
       [80, 40, 18, 71, 55],
       [73, 55, 49, 61, 56],
       [23, 73, 64, 11, 32]])

In [61]:
arrr[0:2,0:2] # row and columns 

array([[ 1, 11],
       [37, 88]])

In [62]:
arrr[0:4,[1,3]] # All rows and 1st and 3rd columns.

array([[11, 45],
       [88, 67],
       [40, 71],
       [55, 61]])

In [63]:
arrr[[1],[1,3]]

array([88, 67])

In [64]:
arrr[arrr>10]

array([11, 81, 45, 37, 88, 41, 67, 65, 80, 40, 18, 71, 55, 73, 55, 49, 61,
       56, 23, 73, 64, 11, 32])

In [65]:
arrr

array([[ 1, 11, 81, 45,  8],
       [37, 88, 41, 67, 65],
       [80, 40, 18, 71, 55],
       [73, 55, 49, 61, 56],
       [23, 73, 64, 11, 32]])

In [66]:
arrr*arrr

array([[   1,  121, 6561, 2025,   64],
       [1369, 7744, 1681, 4489, 4225],
       [6400, 1600,  324, 5041, 3025],
       [5329, 3025, 2401, 3721, 3136],
       [ 529, 5329, 4096,  121, 1024]])

In [67]:
arr1 = np.random.randint(0,5,(3,3))
arr2 = np.random.randint(0,6,(3,3))

arr1

array([[3, 0, 0],
       [3, 4, 4],
       [3, 1, 2]])

In [68]:
arr2

array([[0, 3, 5],
       [5, 3, 2],
       [1, 5, 3]])

In [69]:
arr3 = np.random.randint(0,5,(3,2))

In [70]:
arr3

array([[1, 3],
       [4, 3],
       [1, 2]])

**Different dimension multiplication is possible with matrix not with element wise multiplication**

**In matrix, row will be divided by columns**
**In array multiplication will happen on index wise, 0 index * 0 index**

In [71]:
arr1@arr3 # matrix multiplication

array([[ 3,  9],
       [23, 29],
       [ 9, 16]])

* 2*2  * 3*3 is not possible in matrix.
* 2*3  * 3*3 is possible. 

one Matrix's column should be equal to second matrix's row

# Concept Of Broadcasting

In [72]:
ar_zero = np.zeros((3,4))
ar_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [77]:
ar_zero + a # This is called broadcasting where we insert data of an array into different array.
# All rows of a will be inserted in all rows of ar_zero

# Row and columns should be same same of both arrays.
# Or we can say, shape should be same.
# This is a row wise broadcasting.

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [78]:
b = np.array([5,6,7])
b

# column wise brodcasting.

array([5, 6, 7])

In [79]:
b.reshape(3,1) + ar_zero

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

**We can also use Transpose feature for the same.**
**Transpose will work only on 2D Data**

**T or transpose can be used**

In [83]:
b = np.array([[5,6,7]])
b.T  +ar_zero

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [84]:
arr = np.random.rand(5,4)
arr

array([[0.16749564, 0.48580633, 0.50168416, 0.00735923],
       [0.90996443, 0.32358222, 0.80658276, 0.56544443],
       [0.37444842, 0.77643   , 0.3971347 , 0.91672923],
       [0.96821794, 0.7073453 , 0.50193602, 0.46357214],
       [0.64442877, 0.57688502, 0.27065805, 0.9168682 ]])

In [85]:
np.sqrt(arr) # Square root

array([[0.40926232, 0.69699808, 0.70829666, 0.08578596],
       [0.95392056, 0.56884287, 0.89809953, 0.75196039],
       [0.61192191, 0.88115265, 0.63018624, 0.95745978],
       [0.98398066, 0.84103823, 0.70847443, 0.68086132],
       [0.80276321, 0.75952947, 0.52024806, 0.95753235]])

In [86]:
np.exp(arr) # Exponential

array([[1.18234014, 1.62548515, 1.65150031, 1.00738638],
       [2.48423417, 1.38206978, 2.24023946, 1.7602299 ],
       [1.45418909, 2.17369829, 1.48755629, 2.50109649],
       [2.63324766, 2.02859878, 1.65191633, 1.58974264],
       [1.90489858, 1.78048361, 1.31082675, 2.50144408]])

In [87]:
np.log10(arr) # Logrithmic

array([[-0.77599648, -0.31353683, -0.29956961, -2.13316761],
       [-0.04097558, -0.49001536, -0.09335106, -0.24761007],
       [-0.426608  , -0.10989769, -0.40106216, -0.03775892],
       [-0.01402688, -0.15036853, -0.29935163, -0.33388267],
       [-0.19082508, -0.23891074, -0.56757906, -0.03769309]])

In [96]:
np.random.seed(18)
np.random.rand(2,4)

# Seed means, it won't change the data even when we are using random feature.

array([[0.65037424, 0.50545337, 0.87860147, 0.18184023],
       [0.85223307, 0.75013629, 0.66610167, 0.98789545]])