In [1]:
import pandas as pd

File = pd.read_csv(r"C:\Users\USER\Downloads\SalesforcePractise.csv")

File

First Name Last Name    Phone           Email   Marks
0    Rishiraj     Singh  652452.0   test@test.com      5
1         Raj   Rajawat  554521.0  test1@test.com     10
2       Pawan     Singh   22455.0  test2@test.com      8
3       Mehul    Choksi       NaN  test3@test.com      7
4       Vijay    Maliya   52583.0  test4@test.com      9
5       Vijay    Maliya   52608.0  test4@test.com     67
6       Vijay    Maliya   52633.0  test4@test.com    125
7       Vijay    Maliya   52658.0  test4@test.com    183
8       Vijay    Maliya   52683.0  test4@test.com    241
9       Vijay    Maliya   52708.0  test4@test.com    299
10      Vijay    Maliya   52733.0  test4@test.com    357
11      Vijay    Maliya   52758.0  test4@test.com    415
12      Vijay    Maliya   52783.0  test4@test.com    473
13      Vijay    Maliya   52808.0  test4@test.com    531
14      Vijay    Maliya   52833.0  test4@test.com    589
15      Vijay    Maliya   52858.0  test4@test.com    647
16      Vijay    Maliya   52883.0  test4@test.com    705
17      Vijay    Maliya   52908.0  test4@test.com    763
18      Vijay    Maliya   52933.0  test4@test.com    821
19      Vijay    Maliya   52958.0  test4@test.com    879
20      Vijay    Maliya   52983.0  test4@test.com    937
21      Vijay    Maliya   53008.0  test4@test.com    995
22      Vijay    Maliya   53033.0  test4@test.com   1053
23      Vijay    Maliya   53058.0  test4@test.com   1111
24      Vijay    Maliya   53083.0  test4@test.com   1169
25      Vijay    Maliya   53108.0  test4@test.com   1227
26      Vijay    Maliya   53133.0  test4@test.com   1285
27      Vijay    Maliya   53158.0  test4@test.com   1343
28      Vijay    Maliya   53183.0  test4@test.com   1401
29      Vijay    Maliya   53208.0  test4@test.com   1459
30      Vijay    Maliya   53233.0  test4@test.com   1517
31      Vijay    Maliya   53258.0  test4@test.com   1575
32      Vijay    Maliya   53283.0  test4@test.com   1633
33      Vijay    Maliya   53308.0  test4@test.com   1691
34      Vijay    Maliya   53333.0  test4@test.com   1749
35      Vijay    Maliya   53358.0  test4@test.com   1807
36      Vijay    Maliya   53383.0  test4@test.com   1865

In [2]:
File.head()

First Name Last Name    Phone           Email   Marks
0   Rishiraj     Singh  652452.0   test@test.com      5
1        Raj   Rajawat  554521.0  test1@test.com     10
2      Pawan     Singh   22455.0  test2@test.com      8
3      Mehul    Choksi       NaN  test3@test.com      7
4      Vijay    Maliya   52583.0  test4@test.com      9

In [3]:
File.tail()

First Name Last Name   Phone           Email   Marks
32      Vijay    Maliya  53283.0  test4@test.com   1633
33      Vijay    Maliya  53308.0  test4@test.com   1691
34      Vijay    Maliya  53333.0  test4@test.com   1749
35      Vijay    Maliya  53358.0  test4@test.com   1807
36      Vijay    Maliya  53383.0  test4@test.com   1865

In [4]:
type(File)

pandas.core.frame.DataFrame

In [5]:
type(File.columns)

pandas.core.indexes.base.Index

In [6]:
type(File.dtypes)

pandas.core.series.Series

**In core python it is list, in pandas it is series. We will have be able to perform all actions as we can do with List.**

In [7]:
a = File.dtypes
a

First Name     object
Last Name      object
Phone         float64
Email          object
Marks           int64
dtype: object

In [8]:
a["First Name"]  # We can take action basis on index same as list.

# Series are almost equalient to list.

dtype('O')

In [9]:
a[1]

C:\Users\USER\AppData\Local\Temp\ipykernel_11948\240059899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  a[1]


dtype('O')

In [10]:
a[0:5]

First Name     object
Last Name      object
Phone         float64
Email          object
Marks           int64
dtype: object

In [11]:
a['First Name':'Marks'] 

First Name     object
Last Name      object
Phone         float64
Email          object
Marks           int64
dtype: object

**In case of Series we can do slicing and selection operations basis on index number and index name as well**

In [98]:
a[0:5:2]

First Name     object
Phone         float64
Marks           int64
dtype: object

In [13]:
File

First Name Last Name    Phone           Email   Marks
0    Rishiraj     Singh  652452.0   test@test.com      5
1         Raj   Rajawat  554521.0  test1@test.com     10
2       Pawan     Singh   22455.0  test2@test.com      8
3       Mehul    Choksi       NaN  test3@test.com      7
4       Vijay    Maliya   52583.0  test4@test.com      9
5       Vijay    Maliya   52608.0  test4@test.com     67
6       Vijay    Maliya   52633.0  test4@test.com    125
7       Vijay    Maliya   52658.0  test4@test.com    183
8       Vijay    Maliya   52683.0  test4@test.com    241
9       Vijay    Maliya   52708.0  test4@test.com    299
10      Vijay    Maliya   52733.0  test4@test.com    357
11      Vijay    Maliya   52758.0  test4@test.com    415
12      Vijay    Maliya   52783.0  test4@test.com    473
13      Vijay    Maliya   52808.0  test4@test.com    531
14      Vijay    Maliya   52833.0  test4@test.com    589
15      Vijay    Maliya   52858.0  test4@test.com    647
16      Vijay    Maliya   52883.0  test4@test.com    705
17      Vijay    Maliya   52908.0  test4@test.com    763
18      Vijay    Maliya   52933.0  test4@test.com    821
19      Vijay    Maliya   52958.0  test4@test.com    879
20      Vijay    Maliya   52983.0  test4@test.com    937
21      Vijay    Maliya   53008.0  test4@test.com    995
22      Vijay    Maliya   53033.0  test4@test.com   1053
23      Vijay    Maliya   53058.0  test4@test.com   1111
24      Vijay    Maliya   53083.0  test4@test.com   1169
25      Vijay    Maliya   53108.0  test4@test.com   1227
26      Vijay    Maliya   53133.0  test4@test.com   1285
27      Vijay    Maliya   53158.0  test4@test.com   1343
28      Vijay    Maliya   53183.0  test4@test.com   1401
29      Vijay    Maliya   53208.0  test4@test.com   1459
30      Vijay    Maliya   53233.0  test4@test.com   1517
31      Vijay    Maliya   53258.0  test4@test.com   1575
32      Vijay    Maliya   53283.0  test4@test.com   1633
33      Vijay    Maliya   53308.0  test4@test.com   1691
34      Vijay    Maliya   53333.0  test4@test.com   1749
35      Vijay    Maliya   53358.0  test4@test.com   1807
36      Vijay    Maliya   53383.0  test4@test.com   1865

In [14]:
File.head()

First Name Last Name    Phone           Email   Marks
0   Rishiraj     Singh  652452.0   test@test.com      5
1        Raj   Rajawat  554521.0  test1@test.com     10
2      Pawan     Singh   22455.0  test2@test.com      8
3      Mehul    Choksi       NaN  test3@test.com      7
4      Vijay    Maliya   52583.0  test4@test.com      9

In [15]:
File['First Name'] [5:0:-1]

5    Vijay
4    Vijay
3    Mehul
2    Pawan
1      Raj
Name: First Name, dtype: object

In [16]:
File['First Name'] [::2]

0     Rishiraj
2        Pawan
4        Vijay
6        Vijay
8        Vijay
10       Vijay
12       Vijay
14       Vijay
16       Vijay
18       Vijay
20       Vijay
22       Vijay
24       Vijay
26       Vijay
28       Vijay
30       Vijay
32       Vijay
34       Vijay
36       Vijay
Name: First Name, dtype: object

In [17]:
File.describe() # To get the basic statistics of data. # It is for numeric data. We will see for categorical data/quality data as well.

Phone         Marks
count      36.000000    37.000000
mean    82718.527778   836.513514
std    128730.728727   604.321779
min     22455.000000     5.000000
25%     52776.750000   299.000000
50%     52995.500000   821.000000
75%     53214.250000  1343.000000
max    652452.000000  1865.000000

In [18]:
File.dtypes

First Name     object
Last Name      object
Phone         float64
Email          object
Marks           int64
dtype: object

In [19]:
File_Categorical = File[File.dtypes[File.dtypes == 'object'].index]
# To filter categorical/object datatypes

In [20]:
# Now we can perform describe on categorical data as well.
File_Categorical.describe()

File[['First Name','Last Name']] # To get details of multiple columns, put it in list.
# Type is dataframe not series as we have put it under a list.

First Name Last Name
0    Rishiraj     Singh
1         Raj   Rajawat
2       Pawan     Singh
3       Mehul    Choksi
4       Vijay    Maliya
5       Vijay    Maliya
6       Vijay    Maliya
7       Vijay    Maliya
8       Vijay    Maliya
9       Vijay    Maliya
10      Vijay    Maliya
11      Vijay    Maliya
12      Vijay    Maliya
13      Vijay    Maliya
14      Vijay    Maliya
15      Vijay    Maliya
16      Vijay    Maliya
17      Vijay    Maliya
18      Vijay    Maliya
19      Vijay    Maliya
20      Vijay    Maliya
21      Vijay    Maliya
22      Vijay    Maliya
23      Vijay    Maliya
24      Vijay    Maliya
25      Vijay    Maliya
26      Vijay    Maliya
27      Vijay    Maliya
28      Vijay    Maliya
29      Vijay    Maliya
30      Vijay    Maliya
31      Vijay    Maliya
32      Vijay    Maliya
33      Vijay    Maliya
34      Vijay    Maliya
35      Vijay    Maliya
36      Vijay    Maliya

In [21]:
import numpy as np

In [22]:
File_age_notnull = np.where(File['Marks'].isnull() == False)

In [23]:
File_age_notnull

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36], dtype=int64),)

In [24]:
# to get data from the index location 
Ilocfile = File.iloc[File_age_notnull]
Ilocfile

First Name Last Name    Phone           Email   Marks
0    Rishiraj     Singh  652452.0   test@test.com      5
1         Raj   Rajawat  554521.0  test1@test.com     10
2       Pawan     Singh   22455.0  test2@test.com      8
3       Mehul    Choksi       NaN  test3@test.com      7
4       Vijay    Maliya   52583.0  test4@test.com      9
5       Vijay    Maliya   52608.0  test4@test.com     67
6       Vijay    Maliya   52633.0  test4@test.com    125
7       Vijay    Maliya   52658.0  test4@test.com    183
8       Vijay    Maliya   52683.0  test4@test.com    241
9       Vijay    Maliya   52708.0  test4@test.com    299
10      Vijay    Maliya   52733.0  test4@test.com    357
11      Vijay    Maliya   52758.0  test4@test.com    415
12      Vijay    Maliya   52783.0  test4@test.com    473
13      Vijay    Maliya   52808.0  test4@test.com    531
14      Vijay    Maliya   52833.0  test4@test.com    589
15      Vijay    Maliya   52858.0  test4@test.com    647
16      Vijay    Maliya   52883.0  test4@test.com    705
17      Vijay    Maliya   52908.0  test4@test.com    763
18      Vijay    Maliya   52933.0  test4@test.com    821
19      Vijay    Maliya   52958.0  test4@test.com    879
20      Vijay    Maliya   52983.0  test4@test.com    937
21      Vijay    Maliya   53008.0  test4@test.com    995
22      Vijay    Maliya   53033.0  test4@test.com   1053
23      Vijay    Maliya   53058.0  test4@test.com   1111
24      Vijay    Maliya   53083.0  test4@test.com   1169
25      Vijay    Maliya   53108.0  test4@test.com   1227
26      Vijay    Maliya   53133.0  test4@test.com   1285
27      Vijay    Maliya   53158.0  test4@test.com   1343
28      Vijay    Maliya   53183.0  test4@test.com   1401
29      Vijay    Maliya   53208.0  test4@test.com   1459
30      Vijay    Maliya   53233.0  test4@test.com   1517
31      Vijay    Maliya   53258.0  test4@test.com   1575
32      Vijay    Maliya   53283.0  test4@test.com   1633
33      Vijay    Maliya   53308.0  test4@test.com   1691
34      Vijay    Maliya   53333.0  test4@test.com   1749
35      Vijay    Maliya   53358.0  test4@test.com   1807
36      Vijay    Maliya   53383.0  test4@test.com   1865

In [25]:
# From the above data, name of the person who has the highest marks.

File.iloc[np.where(Ilocfile['Marks'] == max(Ilocfile['Marks'] ))] ['First Name']

36    Vijay
Name: First Name, dtype: object

In [26]:
File[File['Marks'] == min(File['Marks'])] ['First Name']

0    Rishiraj
Name: First Name, dtype: object

In [27]:
# Person who got 1691 marks

File[File['Marks'] == 1691] ['First Name']

33    Vijay
Name: First Name, dtype: object

In [28]:
# Person with 1517 marks

File[File['Marks'] == 1517] ['First Name']

30    Vijay
Name: First Name, dtype: object

In [29]:
titanic_data = pd.read_csv(r"C:\Users\USER\Downloads\titanic.csv")
titanic_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [30]:
titanic_categorical = titanic_data[titanic_data.dtypes[titanic_data.dtypes =='object'].index]
titanic_categorical

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [31]:
titanic_categorical.describe()

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [32]:
# Name of the passenger who have survived and were male.
titanic_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [33]:
survived = np.where(titanic_data[titanic_data['Survived'] == 1])
survived

(array([  0,   0,   0, ..., 341, 341, 341], dtype=int64),
 array([ 0,  1,  2, ...,  9, 10, 11], dtype=int64))

In [34]:
survived_male = np.where(titanic_data.iloc[survived] ['Sex'] == 'male')
survived_male 

(array([   0,    0,    0, ..., 3649, 3649, 3649], dtype=int64),
 array([  0,   1,   2, ..., 339, 340, 341], dtype=int64))

In [35]:
titanic_data.Name[(titanic_data.Survived == 1) & (titanic_data.Sex == 'male')]

17        Williams, Mr. Charles Eugene
21               Beesley, Mr. Lawrence
23        Sloper, Mr. William Thompson
36                    Mamee, Mr. Hanna
55                   Woolner, Mr. Hugh
                    ...               
838                    Chip, Mr. Chang
839               Marechal, Mr. Pierre
857             Daly, Mr. Peter Denis 
869    Johnson, Master. Harold Theodor
889              Behr, Mr. Karl Howell
Name: Name, Length: 109, dtype: object

# Above was the explanation of data filteration. 
# Now we will learn about data manipulation.

In [37]:
# Adding a new column

titanic_data['new column'] = 'rishi'
titanic_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked new column  
0        0         A/5 21171   7.2500   NaN        S      rishi  
1        0          PC 17599  71.2833   C85        C      rishi  
2        0  STON/O2. 3101282   7.9250   NaN        S      rishi  
3        0            113803  53.1000  C123        S      rishi  
4        0            373450   8.0500   NaN        S      rishi  
..     ...               ...      ...   ...      ...        ...  
886      0            211536  13.0000   NaN        S      rishi  
887      0            112053  30.0000   B42        S      rishi  
888      2        W./C. 6607  23.4500   NaN        S      rishi  
889      0            111369  30.0000  C148        C      rishi  
890      0            370376   7.7500   NaN        Q      rishi  

[891 rows x 13 columns]

In [38]:
# Converting list into series
l = [1,2,3,4,5]

pd.Series(l)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [40]:
d = {'Name':'Rishiraj', 'Age': 25, 'mailid':'test@test.com'}
d

{'Name': 'Rishiraj', 'Age': 25, 'mailid': 'test@test.com'}

In [41]:
pd.Series(d)

Name           Rishiraj
Age                  25
mailid    test@test.com
dtype: object

In [47]:
# Converting data into dataframe.
pd.DataFrame(d,index=['Name','Age','mailid'])

Name  Age         mailid
Name    Rishiraj   25  test@test.com
Age     Rishiraj   25  test@test.com
mailid  Rishiraj   25  test@test.com

In [51]:
arr = np.random.randn(2,5)
arr

array([[-1.39236173, -0.01335666,  0.71720168,  0.39988054, -1.17118672],
       [-0.49172908,  1.47036227,  0.17700442, -0.32780385,  0.30420115]])

In [52]:
pd.DataFrame(arr)

0         1         2         3         4
0 -1.392362 -0.013357  0.717202  0.399881 -1.171187
1 -0.491729  1.470362  0.177004 -0.327804  0.304201

In [ ]:
pd.Series(arr)

# It won't work as data is multidimensional.

In [54]:
aru = np.array([1,2,3,4,5])
pd.Series(aru)

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [59]:
aru = np.array([1,2,3,4,5])
ser = pd.Series(aru,index = ['a','b','c','d','e'])

In [60]:
ser['a']

1

In [64]:
# Getting data using iloc
titanic_data.iloc[ser]

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked new column  
1      0          PC 17599  71.2833   C85        C      rishi  
2      0  STON/O2. 3101282   7.9250   NaN        S      rishi  
3      0            113803  53.1000  C123        S      rishi  
4      0            373450   8.0500   NaN        S      rishi  
5      0            330877   8.4583   NaN        Q      rishi

In [67]:
ser.iloc[0] # Even after chaging the indexes it remembers the default index.
# iloc = Integer Location. We can only find data using default index. Even if the index changed to integer it won't work as 
# it takes default index.

1

In [68]:
# For non integer index we can use loc = Location
ser.loc['a']

1

In [69]:
ser1 = pd.Series(aru,index=[45,51,62,75,83])
ser1

45    1
51    2
62    3
75    4
83    5
dtype: int32

In [75]:
dff = pd.DataFrame(np.random.randint(3,6,(4,5)),index = ['a','b','c','d'], columns = ['x','y','z','u','v'])
dff

x  y  z  u  v
a  5  5  4  4  5
b  3  5  5  3  5
c  4  5  4  4  5
d  4  3  3  4  4

In [104]:
dff.iloc[[2,3],[2,3]]

z  u
c  4  4
d  3  4

In [106]:
dff

x  y  z  u  v
a  5  5  4  4  5
b  3  5  5  3  5
c  4  5  4  4  5
d  4  3  3  4  4

In [120]:
dff['new column'] = dff['u'] + dff['v']

In [121]:
dff

x  y  z  u  v  new column
a  5  5  4  4  5           9
b  3  5  5  3  5           8
c  4  5  4  4  5           9
d  4  3  3  4  4           8

# To delete columns
# 1 = Column
# 0 = Row

In [133]:
# Inplace True means the changes will be made and will not change again until we do it.

In [ ]:
dff.drop('x',axis=1,inplace=True)


In [142]:
np.random.seed(23)
data =pd.DataFrame(np.random.randn(4,5),index = ['a','b','c','d'], columns = ['x','y','z','u','v'])
data

x         y         z         u         v
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [164]:
# We have to extract negative value from the above data.

negative_data = data.values[data[::]<0]
list(negative_data)


[-0.7776194131918178,
 -1.0510815639071178,
 -0.3675481161171661,
 -1.1374596907250272,
 -1.3221475225908594,
 -0.34745899102186334,
 -1.0434500017467254,
 -1.0099418765878465,
 -1.8380677677579502,
 -0.9387686311201282]

In [177]:
# Print column and row name of each dataset.

data

for i in data.columns:
    for j in data.index:
        if data[i][j] in negative_data:
            print(i,j,data[i][j])
        

x b -1.0510815639071178
x c -0.34745899102186334
x d -1.0099418765878465
y b -0.3675481161171661
z a -0.7776194131918178
z b -1.1374596907250272
u b -1.3221475225908594
u d -1.8380677677579502
v c -1.0434500017467254
v d -0.9387686311201282


In [170]:
data

x         y         z         u         v
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [182]:
d = {'key1':[0,1,2,3,4,np.nan],'key2':['rishi','singh','raj',4,5,6],'key3':[np.nan,np.nan,np.nan,3,2,8]}
df = pd.DataFrame(d)
df

key1   key2  key3
0   0.0  rishi   NaN
1   1.0  singh   NaN
2   2.0    raj   NaN
3   3.0      4   3.0
4   4.0      5   2.0
5   NaN      6   8.0

In [183]:
df.dropna() # It will drop all rows which have nan.

key1 key2  key3
3   3.0    4   3.0
4   4.0    5   2.0

# axis = 0 = Row
# axis = 1 = Columns

In [184]:
df.dropna(thresh=1)

# Thresh = It will not drop if there's at least 1 non Nan value

key1   key2  key3
0   0.0  rishi   NaN
1   1.0  singh   NaN
2   2.0    raj   NaN
3   3.0      4   3.0
4   4.0      5   2.0
5   NaN      6   8.0

In [ ]:
2:30